/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE ExamenBase PLEASE EDIT ../examen.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
import { Classe } from '../classe';
import { Enseignant } from '../enseignant';
import { Etudiant } from '../etudiant';
import { Matiere } from '../matiere';

/**
 * This is the model of Examen object
 *
 */
export class ExamenBase {

    constructor() { }

    public _id: string;
    public note?: number;
    public place?: string;
    public valid?: Boolean;
    // Relations _classe
    public _classe: Classe | string;
    // Relations _enseignant
    public _enseignant: Enseignant | string;
    // Relations _etudiant
    public _etudiant: Etudiant | string;
    // Relations _matiere
    public _matiere: Matiere | string;
}
