/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE enseignantBaseService PLEASE EDIT ../enseignant.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Enseignant } from '../../domain/alpha_db/enseignant';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Enseignant.service.ts
 */

/*
 * SCHEMA DB Enseignant
 *
	{
		nom: {
			type: 'String',
			required : true
		},
		prenom: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_classe: [{
			type: Schema.ObjectId,
			ref : "Enseignant"
		}],
		_enseignant: {
			type: Schema.ObjectId,
			ref : "Examen"
		},
		_matiere: [{
			type: Schema.ObjectId,
			ref : "Enseignant"
		}],
	}
 *
 */
@Injectable()
export class EnseignantBaseService {

    contextUrl: string = environment.endpoint + '/enseignant';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * EnseignantService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Enseignant): Observable<Enseignant> {
        return this.http
            .post<Enseignant>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * EnseignantService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * EnseignantService.findBy_classe
    *   @description CRUD ACTION findBy_classe
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_classe(id: string): Observable<Enseignant[]> {
        return this.http
            .get<Enseignant[]>(this.contextUrl + '/findBy_classe/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * EnseignantService.findBy_matiere
    *   @description CRUD ACTION findBy_matiere
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_matiere(id: string): Observable<Enseignant[]> {
        return this.http
            .get<Enseignant[]>(this.contextUrl + '/findBy_matiere/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * EnseignantService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Enseignant> {
        return this.http
            .get<Enseignant>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * EnseignantService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Enseignant[]> {
        return this.http
            .get<Enseignant[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * EnseignantService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Enseignant): Observable<Enseignant> {
        return this.http
            .post<Enseignant>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
